#!/bin/bash

#library version
#rustup component add rust-src --toolchain nightly-2025-01-27

export __CARGO_TESTS_ONLY_SRC_ROOT=$(pwd)/library

cleanup() {
    rm -rf /Users/Exelica/Downloads/project/flux-verify-std/dummy
}
trap cleanup EXIT

cargo new dummy
cd dummy
echo '[toolchain]
channel = "nightly-2025-01-27"
components = ["rust-src", "rustc-dev", "llvm-tools", "rustfmt"]' > ./rust-toolchain

case "$(uname -s)" in
    Darwin) target="x86_64-apple-darwin" ;;
    Linux) target="x86_64-unknown-linux-gnu" ;;
    *) echo "Unsupported OS"; exit 1 ;;
esac

FLUXFLAGS="-Fcatch-bugs" cargo flux -Z build-std --target "$target" > ../log.txt 2>&1

cd ..

python3 counter.py